//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove

recipes.remove(<rats:rat_tube_white>);
recipes.remove(<sct:stone_stick>);
recipes.remove(<microblockcbe:stone_rod>);
recipes.remove(<sevendaystomine:kitchenknife>);
recipes.remove(<sevendaystomine:crudeclub>);
recipes.remove(<sevendaystomine:woodenclub>);
recipes.remove(<galaxyspace:rocket_assembler>);
recipes.remove(<extraplanets:tier10_items:1>);
recipes.remove(<galaxyspace:rocket_modules:10>);
recipes.remove(<galaxyspace:rocket_modules:9>);
recipes.remove(<galaxyspace:rocket_modules:8>);
recipes.remove(<galacticraftcore:machine:12>);
recipes.remove(<thermalfoundation:rockwool>);
recipes.remove(<thermalfoundation:rockwool:1>);
recipes.remove(<thermalfoundation:rockwool:2>);
recipes.remove(<thermalfoundation:rockwool:3>);
recipes.remove(<thermalfoundation:rockwool:4>);
recipes.remove(<thermalfoundation:rockwool:5>);
recipes.remove(<thermalfoundation:rockwool:6>);
recipes.remove(<thermalfoundation:rockwool:7>);
recipes.remove(<thermalfoundation:rockwool:15>);
recipes.remove(<thermalfoundation:rockwool:14>);
recipes.remove(<thermalfoundation:rockwool:13>);
recipes.remove(<thermalfoundation:rockwool:12>);
recipes.remove(<thermalfoundation:rockwool:11>);
recipes.remove(<thermalfoundation:rockwool:10>);
recipes.remove(<thermalfoundation:rockwool:9>);
recipes.remove(<thermalfoundation:rockwool:8>);
//recipes.remove(<planetprogression:telescope>);
recipes.remove(<minecraft:slime_ball>);
recipes.remove(<mysticalagriculture:crafting:7>);
recipes.remove(<industrialrenewal:electric_gate>);
//recipes.remove(<spacex:oxygen_loader>);
recipes.remove(<sevendaystomine:wire>);
recipes.remove(<exocraft:fabricator>);
recipes.remove(<techguns:simplemachine:11>);
recipes.remove(<techguns:multiblockmachine>);
recipes.remove(<nuclearcraft:rad_shielding>);
recipes.remove(<nuclearcraft:manufactory>);
recipes.remove(<sct:stone_crafting_table>);
recipes.remove(<techguns:itemshared:3>);
recipes.remove(<techguns:itemshared:57>);
recipes.remove(<techguns:itemshared:1>);
recipes.remove(<techguns:itemshared:70>);
recipes.removeShapeless(<sct:stone_crafting_table>, []);
recipes.remove(<rats:purifying_liquid>);
recipes.remove(<sevendaystomine:scrap_shovel>);
recipes.remove(<sevendaystomine:scrap_axe>);
recipes.remove(<sevendaystomine:scrap_hoe>);
recipes.remove(<sevendaystomine:scrap_pickaxe>);
recipes.remove(<icbmclassic:missile:23>);
recipes.remove(<icbmclassic:missile:22>);
recipes.remove(<icbmclassic:missile:15>);
recipes.remove(<icbmclassic:explosives:15>);
recipes.remove(<icbmclassic:explosives:22>);
recipes.remove(<icbmclassic:explosives:23>);
//recipes.remove(<spacex:oxygen_loader>);
recipes.remove(<minecraft:slime_ball>);
recipes.remove(<woot:anvil>);
recipes.remove(<simplyjetpacks:metaitem:4>);
recipes.remove(<minecraft:ender_pearl>);
recipes.remove(<deepmoblearning:data_model_shulker>);
recipes.remove(<deepmoblearning:data_model_mo_android>);
//recipes.remove(<inspirations:materials:8>);
//recipes.remove(<stone_torches:stone_rod>);
recipes.remove(<techguns:itemshared:33>);
recipes.remove(<techguns:itemshared:70>);
//recipes.remove(<spacex:secondstage>);
//recipes.remove(<spacex:trunk>);
//recipes.remove(<spacex:dragon>);
//recipes.remove(<spacex:falcon9>);
recipes.remove(<galacticraftcore:aluminum_wire>);
//recipes.remove(<galacticraftcore:rocket_workbench>);
//recipes.remove(<matteroverdrive:android_station>);
recipes.remove(<minecraft:nether_star>);
recipes.remove(<sct:stone_crafting_table>);
recipes.remove(<sct:stone_crafting_plate>);
//recipes.remove(<spacex:schematic:3>);
//recipes.remove(<spacex:schematic:2>);
//recipes.remove(<spacex:schematic:1>);
//recipes.remove(<spacex:schematic>);
recipes.removeShapeless(<sct:stone_crafting_plate>, []);
//Don't touch me!
//#Add
recipes.addShaped(<rats:rat_tube_white> * 16, [[<minecraft:glass_pane>, <minecraft:glass_pane>, null],[<minecraft:glass_pane>, <minecraft:glass_pane>, <minecraft:glass_pane>], [null, <minecraft:glass_pane>, <minecraft:glass_pane>]]);
recipes.addShaped(<sevendaystomine:kitchenknife>, [[null, null, <ore:ingotSteel>],[null, <ore:ingotSteel>, <ore:ingotSteel>], [<ore:stickWood>, null, null]]);
recipes.addShaped(<sevendaystomine:crudeclub>, [[null, <ore:plankTreatedWood>, <ore:plankTreatedWood>],[null, <ore:stickWood>, <ore:plankTreatedWood>], [<ore:stickWood>, null, null]]);
recipes.addShaped(<sevendaystomine:woodenclub>, [[null, <ore:plankTreatedWood>, <ore:plankTreatedWood>],[<ore:plankTreatedWood>, <ore:stickWood>, <ore:plankTreatedWood>], [<ore:stickWood>, <ore:plankTreatedWood>, null]]);
recipes.addShaped(<extraplanets:advanced_launch_pad:1> * 5, [[null, null, null],[<galacticraftcore:basic_item:11>, <galacticraftcore:basic_item:11>, <galacticraftcore:basic_item:11>], [<ore:blockAluminium>, <ore:blockAluminium>, <ore:blockAluminium>]]);
recipes.addShaped(<galaxyspace:rocket_assembler>, [[<galaxyspace:gs_basic:3>, <galacticraftcore:rocket_workbench>, <galaxyspace:gs_basic:3>],[<galacticraftcore:machine2>, <galaxyspace:machineframes>, <galacticraftcore:machine2:4>], [<galacticraftcore:aluminum_wire:1>, <galaxyspace:assembly_machine>, <galacticraftcore:aluminum_wire:1>]]);
recipes.addShaped(<extraplanets:tier10_items:1>, [[<nuclearcraft:part:1>, <ore:woolPink>, <nuclearcraft:part:1>],[<nuclearcraft:part:1>, <galacticraftcore:fuel_canister_partial:1>.anyDamage(), <nuclearcraft:part:1>], [<extraplanets:tier10_items:3>, <galacticraftcore:air_vent>, <extraplanets:tier10_items:3>]]);
recipes.addShaped(<galacticraftplanets:volcanic_pickaxe>, [[<galaxyspace:gs_basic:12>, <galaxyspace:gs_basic:12>, <galaxyspace:gs_basic:12>],[null, <ore:rodStone>, null], [null, <ore:rodStone>, null]]);
recipes.addShaped(<galacticraftcore:machine:12>, [[<ore:ingotAluminum>, <minecraft:anvil>.anyDamage(), <ore:ingotAluminum>],[<ore:ingotAluminum>, <ore:ingotCopper>, <ore:ingotAluminum>], [<ore:ingotAluminum>, <ore:gearIron>, <ore:ingotAluminum>]]);
recipes.addShapeless(<minecraft:slime_ball> * 9, [<minecraft:slime>]);
recipes.addShapeless(<minecraft:slime_ball>, [<harvestcraft:jellyfishrawitem>]);
recipes.addShaped(<minecraft:slime_ball> * 8, [[null, <mysticalagriculture:slime_essence>, null],[<mysticalagriculture:slime_essence>, <mysticalagriculture:slime_essence>, <mysticalagriculture:slime_essence>], [null, <mysticalagriculture:slime_essence>, null]]);
recipes.addShaped(<minecraft:slime_ball>, [[<ore:dyeGreen>, <minecraft:sugar>, <ore:dyeGreen>],[<minecraft:sugar>, null, <minecraft:sugar>], [<ore:dyeGreen>, <minecraft:sugar>, <ore:dyeGreen>]]);
recipes.addShaped(<mysticalagriculture:crafting:7>, [[<ore:dyeBlack>, <ore:dyeOrange>, null],[<ore:dyeCyan>, <ore:dye>, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool:14>, [[<ore:blockRockwool>, <ore:dyeOrange>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool:13>, [[<ore:blockRockwool>, <ore:dyeMagenta>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool:12>, [[<ore:blockRockwool>, <ore:dyeLightBlue>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool:11>, [[<ore:blockRockwool>, <ore:dyeYellow>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool:10>, [[<ore:blockRockwool>, <ore:dyeLime>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool:9>, [[<ore:blockRockwool>, <ore:dyePink>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool:8>, [[<ore:blockRockwool>, <ore:dyeGray>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool:7>, [[<ore:blockRockwool>, <ore:dyeLightGray>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool:6>, [[<ore:blockRockwool>, <ore:dyeCyan>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool:5>, [[<ore:blockRockwool>, <ore:dyePurple>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool:4>, [[<ore:blockRockwool>, <ore:dyeBlue>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool:4>, [[<ore:blockRockwool>, <ore:dyeBlue>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool:3>, [[<ore:blockRockwool>, <ore:dyeBrown>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool:2>, [[<ore:blockRockwool>, <ore:dyeGreen>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool:1>, [[<ore:blockRockwool>, <ore:dyeRed>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool>, [[<ore:blockRockwool>, <ore:dyeBlack>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<thermalfoundation:rockwool:15>, [[<ore:blockRockwool>, <ore:dyeWhite>, null],[null, null, null], [null, null, null]]);
recipes.addShapeless(<sevendaystomine:cloth>, [<minecraft:leather>]);
furnace.addRecipe(<minecraft:leather>, <sevendaystomine:cloth>, 0.0);
recipes.addShaped(<industrialrenewal:electric_gate> * 2, [[<ore:plateIron>, <ore:stickIron>, <thermalfoundation:material:32>],[<ore:ingotIron>, <ore:stickIron>, <ore:ingotIron>], [<ore:ingotIron>, <ore:stickIron>, <ore:ingotIron>]]);
//recipes.addShaped(<industrialrenewal:electric_gate> * 2, [[<thermalfoundation:material:32>, <immersiveengineering:material:1>, <thermalfoundation:material:32>],[<minecraft:iron_ingot>, <immersiveengineering:material:1>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <immersiveengineering:material:1>, <minecraft:iron_ingot>]]);
//recipes.addShaped(<industrialrenewal:electric_gate> * 2, [[<ore:ingotIron>, <ore:stickIron>, <ore:ingotIron>],[<ore:ingotIron>, <ore:stickIron>, <ore:ingotIron>], [<ore:ingotIron>, <ore:stickIron>, <ore:ingotIron>]]);
//recipes.addShapeless(<spacex:ingot_lithium>, [<nuclearcraft:ingot:6>]);
furnace.addRecipe(<immersiveintelligence:ore:1> * 2, <densemetals:dense_zinc_ore>, 0.0);
furnace.addRecipe(<immersiveintelligence:ore:2> * 2, <densemetals:dense_tungsten_ore>, 0.0);
furnace.addRecipe(<nuclearcraft:ore:4> * 2, <densemetals:dense_uranium_ore>, 0.0);
furnace.addRecipe(<nuclearcraft:ore:3> * 2, <densemetals:dense_thorium_ore>, 0.0);
furnace.addRecipe(<nuclearcraft:ore:7> * 2, <densemetals:dense_magnesium_ore>, 0.0);
furnace.addRecipe(<nuclearcraft:ore:5> * 2, <densemetals:dense_boron_ore>, 0.0);
recipes.addShaped(<sevendaystomine:wire>, [[null, null, null],[<ore:nuggetCopper>, <ore:nuggetCopper>, <ore:nuggetCopper>], [null, null, null]]);
recipes.addShaped(<exocraft:unit_stryder>, [[<exocraft:redstone_circuit>, <exocraft:reinforced_iron_plate>, null],[<exocraft:reinforced_iron_plate>, null, null], [null, null, null]]);
recipes.addShaped(<exocraft:unit_ogre>, [[<exocraft:reinforced_iron_plate>, null, null],[null, <exocraft:redstone_circuit>, null], [null, null, <exocraft:reinforced_iron_plate>]]);
recipes.addShaped(<exocraft:unit_legion>, [[null, null, <exocraft:reinforced_iron_plate>],[null, <exocraft:redstone_circuit>, null], [<exocraft:reinforced_iron_plate>, null, null]]);
recipes.addShaped(<exocraft:unit_ion>, [[null, <exocraft:reinforced_iron_plate>, null],[null, <exocraft:redstone_circuit>, null], [null, <exocraft:reinforced_iron_plate>, null]]);
recipes.addShaped(<exocraft:unit_atlas>, [[null, null, null],[<exocraft:reinforced_iron_plate>, <exocraft:redstone_circuit>, <exocraft:reinforced_iron_plate>], [null, null, null]]);
recipes.addShaped(<exocraft:redstone_circuit>, [[null, <minecraft:redstone>, null],[<minecraft:redstone>, <galacticraftcore:basic_item:11>, <minecraft:redstone>], [null, <minecraft:redstone>, null]]);
recipes.addShaped(<exocraft:industrial_multi_tool>, [[<minecraft:iron_shovel>, <minecraft:iron_pickaxe>, <minecraft:iron_axe>],[null, <exocraft:machine_case>, null], [null, null, null]]);
recipes.addShapeless(<exocraft:industrial_miner>, [<exocraft:machine_case>,<minecraft:iron_pickaxe>]);
recipes.addShapeless(<exocraft:industrial_excavator>, [<exocraft:machine_case>,<minecraft:iron_shovel>]);
recipes.addShaped(<exocraft:machine_case>, [[<exocraft:reinforced_iron_plate>, <exocraft:reinforced_iron_plate>, <exocraft:reinforced_iron_plate>],[<exocraft:reinforced_iron_plate>, <exocraft:energy_core>, <exocraft:reinforced_iron_plate>], [<exocraft:reinforced_iron_plate>, <exocraft:reinforced_iron_plate>, <exocraft:reinforced_iron_plate>]]);
recipes.addShaped(<exocraft:stryder_boots>, [[<exocraft:unit_stryder>, null, <exocraft:energy_core>],[<exocraft:reinforced_iron_plate>, null, <exocraft:reinforced_iron_plate>], [null, null, null]]);
recipes.addShaped(<exocraft:stryder_leggings>, [[<exocraft:reinforced_iron_plate>, <exocraft:unit_stryder>, <exocraft:reinforced_iron_plate>],[<exocraft:reinforced_iron_plate>, <exocraft:energy_core>, <exocraft:reinforced_iron_plate>], [<exocraft:reinforced_iron_plate>, null, <exocraft:reinforced_iron_plate>]]);
recipes.addShaped(<exocraft:stryder_chestplate>, [[<exocraft:reinforced_iron_plate>, <exocraft:unit_stryder>, <exocraft:reinforced_iron_plate>],[<exocraft:reinforced_iron_plate>, <exocraft:energy_core>, <exocraft:reinforced_iron_plate>], [<exocraft:reinforced_iron_plate>, <exocraft:reinforced_iron_plate>, <exocraft:reinforced_iron_plate>]]);
recipes.addShaped(<exocraft:stryder_helmet>, [[<exocraft:reinforced_iron_plate>, <exocraft:unit_stryder>, <exocraft:reinforced_iron_plate>],[<exocraft:reinforced_iron_plate>, <exocraft:energy_core>, <exocraft:reinforced_iron_plate>], [null, null, null]]);
recipes.addShaped(<exocraft:ogre_boots>, [[<exocraft:unit_ogre>, null, <exocraft:energy_core>],[<exocraft:reinforced_iron_plate>, null, <exocraft:reinforced_iron_plate>], [null, null, null]]);
recipes.addShaped(<exocraft:ogre_leggings>, [[<exocraft:reinforced_iron_plate>, <exocraft:unit_ogre>, <exocraft:reinforced_iron_plate>],[<exocraft:reinforced_iron_plate>, <exocraft:energy_core>, <exocraft:reinforced_iron_plate>], [<exocraft:reinforced_iron_plate>, null, <exocraft:reinforced_iron_plate>]]);
recipes.addShaped(<exocraft:ogre_chestplate>, [[<exocraft:reinforced_iron_plate>, <exocraft:unit_ogre>, <exocraft:reinforced_iron_plate>],[<exocraft:reinforced_iron_plate>, <exocraft:energy_core>, <exocraft:reinforced_iron_plate>], [<exocraft:reinforced_iron_plate>, <exocraft:reinforced_iron_plate>, <exocraft:reinforced_iron_plate>]]);
recipes.addShaped(<exocraft:ogre_helmet>, [[<exocraft:reinforced_iron_plate>, <exocraft:unit_ogre>, <exocraft:reinforced_iron_plate>],[<exocraft:reinforced_iron_plate>, <exocraft:energy_core>, <exocraft:reinforced_iron_plate>], [null, null, null]]);
recipes.addShaped(<exocraft:legion_boots>, [[<exocraft:unit_legion>, null, <exocraft:energy_core>],[<exocraft:reinforced_iron_plate>, null, <exocraft:reinforced_iron_plate>], [null, null, null]]);
recipes.addShaped(<exocraft:legion_leggings>, [[<exocraft:reinforced_iron_plate>, <exocraft:unit_legion>, <exocraft:reinforced_iron_plate>],[<exocraft:reinforced_iron_plate>, <exocraft:energy_core>, <exocraft:reinforced_iron_plate>], [<exocraft:reinforced_iron_plate>, null, <exocraft:reinforced_iron_plate>]]);
recipes.addShaped(<exocraft:legion_chestplate>, [[<exocraft:reinforced_iron_plate>, <exocraft:unit_legion>, <exocraft:reinforced_iron_plate>],[<exocraft:reinforced_iron_plate>, <exocraft:energy_core>, <exocraft:reinforced_iron_plate>], [<exocraft:reinforced_iron_plate>, <exocraft:reinforced_iron_plate>, <exocraft:reinforced_iron_plate>]]);
recipes.addShaped(<exocraft:legion_helmet>, [[<exocraft:reinforced_iron_plate>, <exocraft:unit_legion>, <exocraft:reinforced_iron_plate>],[<exocraft:reinforced_iron_plate>, <exocraft:energy_core>, <exocraft:reinforced_iron_plate>], [null, null, null]]);
recipes.addShaped(<exocraft:ion_boots>, [[<exocraft:unit_ion>, null, <exocraft:energy_core>],[<exocraft:reinforced_iron_plate>, null, <exocraft:reinforced_iron_plate>], [null, null, null]]);
recipes.addShaped(<exocraft:ion_leggings>, [[<exocraft:reinforced_iron_plate>, <exocraft:unit_ion>, <exocraft:reinforced_iron_plate>],[<exocraft:reinforced_iron_plate>, <exocraft:energy_core>, <exocraft:reinforced_iron_plate>], [<exocraft:reinforced_iron_plate>, null, <exocraft:reinforced_iron_plate>]]);
recipes.addShaped(<exocraft:ion_chestplate>, [[<exocraft:reinforced_iron_plate>, <exocraft:unit_ion>, <exocraft:reinforced_iron_plate>],[<exocraft:reinforced_iron_plate>, <exocraft:energy_core>, <exocraft:reinforced_iron_plate>], [<exocraft:reinforced_iron_plate>, <exocraft:reinforced_iron_plate>, <exocraft:reinforced_iron_plate>]]);
recipes.addShaped(<exocraft:ion_helmet>, [[<exocraft:reinforced_iron_plate>, <exocraft:reinforced_iron_plate>, <exocraft:reinforced_iron_plate>],[<exocraft:reinforced_iron_plate>, <exocraft:unit_ion>, <exocraft:reinforced_iron_plate>], [null, <exocraft:energy_core>, null]]);
recipes.addShaped(<exocraft:energy_core>, [[<minecraft:gold_ingot>, <minecraft:redstone>, <minecraft:gold_ingot>],[<minecraft:redstone>, <exocraft:lava_crystal>, <minecraft:redstone>], [<minecraft:gold_ingot>, <minecraft:redstone>, <minecraft:gold_ingot>]]);
recipes.addShaped(<exocraft:atlas_boots>, [[<exocraft:unit_atlas>, null, <exocraft:energy_core>],[<exocraft:reinforced_iron_plate>, null, <exocraft:reinforced_iron_plate>], [null, null, null]]);
recipes.addShaped(<exocraft:atlas_leggings>, [[<exocraft:reinforced_iron_plate>, <exocraft:unit_atlas>, <exocraft:reinforced_iron_plate>],[<exocraft:reinforced_iron_plate>, <exocraft:energy_core>, <exocraft:reinforced_iron_plate>], [<exocraft:reinforced_iron_plate>, null, <exocraft:reinforced_iron_plate>]]);
recipes.addShaped(<exocraft:atlas_chestplate>, [[<exocraft:reinforced_iron_plate>, <exocraft:energy_core>, <exocraft:reinforced_iron_plate>],[<exocraft:reinforced_iron_plate>, <exocraft:unit_atlas>, <exocraft:reinforced_iron_plate>], [<exocraft:reinforced_iron_plate>, <exocraft:reinforced_iron_plate>, <exocraft:reinforced_iron_plate>]]);
recipes.addShaped(<exocraft:atlas_helmet>, [[<exocraft:reinforced_iron_plate>, <exocraft:unit_atlas>, <exocraft:reinforced_iron_plate>],[<exocraft:reinforced_iron_plate>, <exocraft:energy_core>, <exocraft:reinforced_iron_plate>], [null, null, null]]);
recipes.addShaped(<exocraft:reinforced_iron_plate>, [[<minecraft:diamond>, <ore:ingotIron>, <minecraft:diamond>],[<ore:ingotIron>, <ore:ingotIron>, <ore:ingotIron>], [<minecraft:diamond>, <ore:ingotIron>, <minecraft:diamond>]]);
recipes.addShaped(<ftbquests:lootcrate>.withTag({type: "random_rewards_legendary_"}), [[<ftbquests:lootcrate>.withTag({type: "random_reward_rare_"}).onlyWithTag({type: "random_reward_rare_"}), <ftbquests:lootcrate>.withTag({type: "random_reward_rare_"}).onlyWithTag({type: "random_reward_rare_"}), null],[<ftbquests:lootcrate>.withTag({type: "random_reward_rare_"}).onlyWithTag({type: "random_reward_rare_"}), <ftbquests:lootcrate>.withTag({type: "random_reward_rare_"}).onlyWithTag({type: "random_reward_rare_"}), null], [null, null, null]]);
recipes.addShaped(<ftbquests:lootcrate>.withTag({type: "random_reward_rare_"}), [[<ftbquests:lootcrate>.withTag({type: "random_reward_common_"}).onlyWithTag({type: "random_reward_common_"}), <ftbquests:lootcrate>.withTag({type: "random_reward_common_"}).onlyWithTag({type: "random_reward_common_"}), null],[<ftbquests:lootcrate>.withTag({type: "random_reward_common_"}).onlyWithTag({type: "random_reward_common_"}), <ftbquests:lootcrate>.withTag({type: "random_reward_common_"}).onlyWithTag({type: "random_reward_common_"}), null], [null, null, null]]);
recipes.addShaped(<minecraft:lit_pumpkin>, [[null, <minecraft:pumpkin>, null],[null, <sevendaystomine:torchlit>, null], [null, null, null]]);
//recipes.addShaped(<inspirations:torch_lever>, [[<chisel:cobblestone2:3>, <sevendaystomine:torchlit>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<immersiveengineering:cloth_device:1>, [[null, <immersiveengineering:material:5>, null],[<immersiveengineering:material:5>, <sevendaystomine:torchlit>, <immersiveengineering:material:5>], [null, <immersiveengineering:treated_wood_slab:2>, null]]);
recipes.addShaped(<openblocks:builder_guide>, [[<ore:blockGlass>, <minecraft:redstone>, <ore:blockGlass>],[<minecraft:ender_pearl>, <sevendaystomine:torchlit>, <minecraft:ender_pearl>], [<ore:blockGlass>, <minecraft:redstone>, <ore:blockGlass>]]);
recipes.addShaped(<rats:jack_o_ratern>, [[null, <minecraft:pumpkin>, null],[null, <rats:raw_rat>, null], [null, <sevendaystomine:torchlit>, null]]);
recipes.addShaped(<torchmaster:terrain_lighter>, [[<minecraft:stick>, <sevendaystomine:torchlit>, <minecraft:stick>],[<ore:logWood>, <minecraft:chest>, <ore:logWood>], [<minecraft:stone>, <minecraft:stone>, <minecraft:stone>]]);
recipes.addShaped(<torchmaster:mega_torch>, [[<sevendaystomine:torchlit>, <sevendaystomine:torchlit>, <sevendaystomine:torchlit>],[<minecraft:diamond>, <ore:logWood>, <minecraft:diamond>], [<minecraft:gold_block>, <ore:logWood>, <minecraft:gold_block>]]);
recipes.addShaped(<v0idssmartbackpacks:upgrade_lighting>, [[null, <sevendaystomine:torchlit>, null],[<sevendaystomine:torchlit>, <v0idssmartbackpacks:upgrade_base>, <sevendaystomine:torchlit>], [<minecraft:dispenser>, <sevendaystomine:torchlit>, <minecraft:dispenser>]]);
//recipes.addShapeless(<quark:arrow_torch>, [<minecraft:arrow>,<sevendaystomine:torchlit>]);
//recipes.addShapeless(<essentials:candle_lilypad>, [<minecraft:waterlily>,<sevendaystomine:torchlit>]);
recipes.addShaped(<simplyjetpacks:metaitem>, [[null, <sevendaystomine:torchlit>, null],[<sevendaystomine:torchlit>, <ore:dustCoal>, <sevendaystomine:torchlit>], [null, <sevendaystomine:torchlit>, null]]);
recipes.addShapeless(<darkutils:sneaky_torch>, [<darkutils:sneaky>,<sevendaystomine:torchlit>]);
recipes.addShaped(<techguns:simplemachine:11>, [[<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:14>, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:9>, <minecraft:furnace>, <galacticraftcore:basic_item:9>], [<ore:ingotAluminum>, <ore:ingotAluminum>, <ore:ingotAluminum>]]);
recipes.addShaped(<techguns:multiblockmachine> * 4, [[<galacticraftcore:basic_item:9>, <techguns:itemshared:59>, <galacticraftcore:basic_item:9>],[<galacticraftcore:basic_item:14>, <techguns:itemshared:70>, <galacticraftcore:basic_item:14>], [<galacticraftcore:basic_item:9>, <ore:circuitElite>, <galacticraftcore:basic_item:9>]]);
recipes.addShaped(<nuclearcraft:manufactory>, [[<galacticraftcore:basic_item:9>, <minecraft:redstone>, <galacticraftcore:basic_item:9>],[<minecraft:flint>, <minecraft:piston>, <minecraft:flint>], [<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:14>, <galacticraftcore:basic_item:9>]]);
recipes.addShaped(<nuclearcraft:rad_shielding>, [[<ore:ingotLead>, <nuclearcraft:part>, <ore:ingotLead>],[<nuclearcraft:part>, <ore:ingotIron>, <nuclearcraft:part>], [<ore:ingotLead>, <nuclearcraft:part>, <ore:ingotLead>]]);
//recipes.addShaped(<nuclearcraft:manufactory>, [[<ore:ingotLead>, <minecraft:redstone>, <ore:ingotLead>],[<minecraft:flint>, <minecraft:piston>, <minecraft:flint>], [<ore:ingotLead>, <techguns:itemshared:70>, <ore:ingotLead>]]);
recipes.addShaped(<techguns:itemshared:70>, [[<techguns:itemshared:62>, <galacticraftcore:basic_item:9>, <techguns:itemshared:62>],[<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:14>, <galacticraftcore:basic_item:9>], [<techguns:itemshared:62>, <galacticraftcore:basic_item:9>, <techguns:itemshared:62>]]);
recipes.addShaped(<minecraft:totem_of_undying>, [[<cyberware:body_part:8>, <cyberware:body_part>, <cyberware:body_part:9>],[<extrautils2:ingredients:11>, <cyberware:body_part:2>, <extrautils2:ingredients:11>], [<cyberware:body_part:10>, <extrautils2:ingredients:11>, <cyberware:body_part:11>]]);
recipes.addShapeless(<sct:stone_crafting_table>, [<sct:stone_crafting_plate>]);
recipes.addShapeless(<sevendaystomine:antibiotics>, [<minecraft:sugar>,<minecraft:potion>.withTag({Potion: "minecraft:water"}).onlyWithTag({Potion: "minecraft:water"})]);
recipes.addShaped(<apexguns:heavy_ammo> * 20, [[null, <minecraft:gunpowder>, null],[null, <pickletweaks:dye_powder:9>, null], [null, <immersiveintelligence:material_ingot>, null]]);
recipes.addShaped(<apexguns:light_ammo> * 20, [[null, <minecraft:gunpowder>, null],[null, <minecraft:dye:14>, null], [null, <immersiveintelligence:material_ingot>, null]]);
recipes.addShaped(<apexguns:kraber_ammo>, [[null, <minecraft:gunpowder>, null],[null, <immersiveintelligence:material_ingot>, null], [null, <techguns:itemshared:84>, null]]);
recipes.addShapeless(<rats:purifying_liquid>, [<minecraft:sugar>,<sevendaystomine:bottledmurkywater>]);
recipes.addShaped(<apexguns:r99>, [[<immersiveintelligence:material_ingot>, <immersiveengineering:material:26>, <immersiveintelligence:material_ingot:4>],[<immersiveintelligence:material_ingot:4>, <techguns:itemshared:57>, null], [null, null, null]]);
recipes.addShaped(<apexguns:r301>, [[<immersiveintelligence:material_ingot>, <immersiveintelligence:material:1>, <immersiveintelligence:material_ingot:4>],[<immersiveintelligence:material_ingot:4>, <techguns:itemshared:57>, null], [null, null, null]]);
recipes.addShaped(<apexguns:spitfire>, [[<immersiveintelligence:material_ingot>, <immersiveintelligence:material:1>, <immersiveintelligence:material_ingot:4>],[<immersiveintelligence:material_ingot>, <techguns:itemshared:58>, null], [null, null, null]]);
recipes.addShaped(<apexguns:rifle3030>, [[<immersiveintelligence:material_ingot>, <immersiveintelligence:material:1>, <immersiveintelligence:material_ingot>],[<immersiveintelligence:material_ingot>, <techguns:itemshared:58>, null], [null, null, null]]);
recipes.addShaped(<apexguns:kraber>, [[<immersiveintelligence:material_ingot>, <immersiveintelligence:material:3>, <immersiveintelligence:material_ingot>],[<immersiveintelligence:material_ingot>, <techguns:itemshared:59>, null], [null, null, null]]);
furnace.addRecipe(<sevendaystomine:bottledmurkywater>, <minecraft:potion>.withTag({Potion: "minecraft:water"}).onlyWithTag({Potion: "minecraft:water"}), 0.0);
//recipes.addShaped(<sevendaystomine:antibiotics>, [[null, <minecraft:sugar>, null],[null,  <minecraft:potion>.withTag({Potion: "minecraft:water"}).onlyWithTag({Potion: "minecraft:water"}), null], [null, null, null]]);
recipes.addShaped(<sevendaystomine:scrap_hoe>, [[<sevendaystomine:scrapiron>, <sevendaystomine:scrapiron>, null],[null, <ore:rodStone>, null], [null, <ore:rodStone>, null]]);
recipes.addShaped(<sevendaystomine:scrap_axe>, [[<sevendaystomine:scrapiron>, <sevendaystomine:scrapiron>, null],[<sevendaystomine:scrapiron>, <ore:rodStone>, null], [null, <ore:rodStone>, null]]);
recipes.addShaped(<sevendaystomine:scrap_shovel>, [[null, <sevendaystomine:scrapiron>, null],[null, <ore:rodStone>, null], [null, <ore:rodStone>, null]]);
recipes.addShaped(<sevendaystomine:scrap_pickaxe>, [[<sevendaystomine:scrapiron>, <sevendaystomine:scrapiron>, <sevendaystomine:scrapiron>],[null, <ore:rodStone>, null], [null, <ore:rodStone>, null]]);
recipes.addShaped(<minecraft:stone_button>, [[null, null, null],[null, <minecraft:cobblestone>, null], [null, null, null]]);
recipes.addShapeless(<minecraft:water_bucket>, [<sevendaystomine:bottledwater>,<sevendaystomine:emptycan>]);
recipes.addShapeless(<minecraft:bucket>, [<sevendaystomine:emptycan>]);
recipes.addShapeless(<minecraft:leather>, [<sevendaystomine:cloth>,<sevendaystomine:cloth>]);
recipes.addShaped(<extraplanets:tier10_items:2>, [
    [null, <extraplanets:tier10_items:3>, null],
    [<extraplanets:tier10_items:3>, <extraplanets:tier10_items:3>, <extraplanets:tier10_items:3>],
    [<extraplanets:tier10_items:3>, null, <extraplanets:tier10_items:3>]
]);
recipes.addShaped(<extraplanets:electric_parts:1>, [
    [<thermalfoundation:material:131>,<galacticraftplanets:item_basic_mars:2>,<thermalfoundation:material:131>],
    [<galacticraftplanets:item_basic_mars:2>,<thermalfoundation:material:131>,<galacticraftplanets:item_basic_mars:2>],
    [<thermalfoundation:material:131>,<galacticraftplanets:item_basic_mars:2>,<thermalfoundation:material:131>]
]);
recipes.addShaped(<minecraft:bed>, [[null, null, null],[<minecraft:string>, <minecraft:string>, <minecraft:string>], [<ore:plankWood>, <ore:plankWood>, <ore:plankWood>]]);
//recipes.addShapeless(<spacex:dragon>, [<spacex:dragon_used>.noReturn(),<galacticraftcore:standard_wrench>.anyDamage()]);
//recipes.addShapeless(<spacex:oxygen_loader>, [<spacex:oxygen_unloader>]);
//recipes.addShaped(<spacex:oxygen_loader>, [[<galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:9>, <galacticraftcore:basic_item:9>],[<extraplanets:oxygen_tank_light_full_red:*>, <galacticraftcore:fuel_loader>, <extraplanets:oxygen_tank_light_full_red:*>], [<galacticraftcore:basic_item:9>, <galacticraftcore:fluid_pipe>, <galacticraftcore:basic_item:9>]]);
//furnace.addRecipe(<spacex:ingot_lithium>, <mekanism:otherdust:4>, 0.0);
recipes.addShaped(<exocraft:unit_atlas>, [[null, <exocraft:reinforced_iron_plate>, null],[<exocraft:reinforced_iron_plate>, <exocraft:redstone_circuit>, <exocraft:reinforced_iron_plate>], [null, <exocraft:reinforced_iron_plate>, null]]);
recipes.addShapeless(<minecraft:slime_ball> * 9, [<minecraft:slime>]);
recipes.addShaped(<minecraft:slime_ball> * 4, [[<minecraft:dye:2>, <minecraft:sugar>, <minecraft:dye:2>],[<minecraft:sugar>, <malisisswitches:greenstone_dust>, <minecraft:sugar>], [<minecraft:dye:2>, <minecraft:sugar>, <minecraft:dye:2>]]);
recipes.addShaped(<woot:anvil>, [[<ore:blockCopper>, <ore:blockCopper>, <ore:blockCopper>],[null, <ore:blockCopper>, null], [<minecraft:obsidian>, <minecraft:obsidian>, <minecraft:obsidian>]]);
recipes.addShapeless(<minecraft:ender_pearl> * 4, [<deepmoblearning:living_matter_extraterrestrial>,<minecraft:chorus_fruit_popped>]);
//recipes.addShapeless(<minecraft:cactus> * 4, [<deepmoblearning:living_matter_overworldian>,<quark:reed_block>]);
recipes.addShaped(<simplyjetpacks:metaitem:4>, [[null, null, null],[<minecraft:leather>, <minecraft:iron_ingot>, <minecraft:leather>], [null, null, null]]);
recipes.addShapeless(<minecraft:ender_pearl> * 4, [<forge:bucketfilled>.withTag({FluidName: "ender", Amount: 1000}).onlyWithTag({FluidName: "ender", Amount: 1000}),<thermalfoundation:material:1025>]);
recipes.addShapeless(<minecraft:ender_pearl>, [<thermalfoundation:material:895>, <thermalfoundation:material:1025>]);
recipes.addShapeless(<deepmoblearning:data_model_shulker>, [<deepmoblearning:data_model_blank>,<minecraft:chorus_fruit>]);
recipes.addShaped(<minecraft:dragon_egg>, [[<minecraft:end_crystal>, <extraplanets:tier11_items:2>, <minecraft:end_crystal>],[<extraplanets:tier11_items:2>, <minecraft:egg>, <extraplanets:tier11_items:2>], [<minecraft:end_crystal>, <extraplanets:tier11_items:2>, <minecraft:end_crystal>]]);
recipes.addShapeless(<minecraft:reeds> * 4, [<minecraft:stick>,<minecraft:stick>,<minecraft:wheat_seeds>,<deepmoblearning:living_matter_overworldian>]);
recipes.addShapeless(<deepmoblearning:data_model_mo_android>, [<deepmoblearning:data_model_blank>,<matteroverdrive:tritanium_ingot>]);
//recipes.addShaped(<stone_torches:stone_rod> * 3, [[null, <minecraft:cobblestone>, null],[null, <minecraft:cobblestone>, null], [null, <minecraft:cobblestone>, null]]);
//recipes.addShaped(<inspirations:materials:8> * 3, [[null, null, <minecraft:cobblestone>],[null, <minecraft:cobblestone>, null], [<minecraft:cobblestone>, null, null]]);
recipes.addShaped(<sct:stone_stick> * 2, [[null, null, null],[null, <minecraft:cobblestone>, null], [null, <minecraft:cobblestone>, null]]);
recipes.addShapeless(<minecraft:ender_pearl> * 4, [<deepmoblearning:living_matter_extraterrestrial>,<minecraft:slime_ball>]);
recipes.addShapeless(<minecraft:water_bucket>, [<deepmoblearning:living_matter_overworldian>,<minecraft:bucket>]);
recipes.addShapeless(<minecraft:lava_bucket>, [<deepmoblearning:living_matter_hellish>,<minecraft:bucket>]);
recipes.addShaped(<techguns:itemshared:33>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>],[null, <techguns:itemshared:69>, <minecraft:iron_nugget>], [null, <techguns:itemshared:57>, <minecraft:iron_nugget>]]);
recipes.addShaped(<techguns:itemshared:70>, [[<techguns:itemshared:62>, <minecraft:redstone>, <techguns:itemshared:62>],[<minecraft:iron_ingot>, <techguns:itemshared:69>, <minecraft:iron_ingot>], [<techguns:itemshared:62>, <minecraft:redstone>, <techguns:itemshared:62>]]);
recipes.addShapeless(<minecraft:cobblestone> * 2, [<wasteland_meteors:meteor_block>,<wasteland_meteors:meteor_block>]);
recipes.addShaped(<minecraft:iron_sword>, [[null, <minecraft:iron_ingot>, null],[null, <ore:ingotIron>, null], [null, <ore:rodStone>, null]]);
recipes.addShaped(<minecraft:iron_axe>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, null],[<minecraft:iron_ingot>, <ore:rodStone>, null], [null, <ore:rodStone>, null]]);
recipes.addShaped(<minecraft:iron_hoe>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, null],[null, <ore:rodStone>, null], [null, <ore:rodStone>, null]]);
recipes.addShaped(<minecraft:iron_pickaxe>, [[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>],[null, <ore:rodStone>, null], [null, <ore:rodStone>, null]]);
recipes.addShaped(<minecraft:iron_shovel>, [[null, <minecraft:iron_ingot>, null],[null, <ore:rodStone>, null], [null, <ore:rodStone>, null]]);
recipes.addShapeless(<atomicscience:yellow_cake>, [<techguns:itemshared:97>]);
recipes.addShapeless(<techguns:itemshared:97> * 8, [<deepmoblearning:living_matter_extraterrestrial>,<extraplanets:tier11_items:3>,<minecraft:gunpowder>]);
recipes.addShapeless(<minecraft:string> * 8, [<deepmoblearning:living_matter_overworldian>,<randomthings:grassseeds>]);
recipes.addShaped(<galacticraftcore:aluminum_wire> * 3, [[null, null, null],[<ore:ingotAluminum>, <ore:ingotAluminum>, <ore:ingotAluminum>], [null, null, null]]);
//recipes.addShapeless(<spacex:trunk>, [<spacex:trunk_used>.noReturn(),<galacticraftcore:standard_wrench>.anyDamage()]);
//recipes.addShapeless(<spacex:secondstage>, [<spacex:secondstage_used>.noReturn(),<galacticraftcore:standard_wrench>.anyDamage()]);
//recipes.addShapeless(<spacex:falcon9>, [<spacex:falcon9_used>.noReturn(),<galacticraftcore:standard_wrench>.anyDamage()]);
recipes.addShapeless(<galacticraftcore:dungeonfinder>, [<openblocks:golden_eye>,<minecraft:compass>]);
recipes.addShaped(<minecraft:stone_sword>, [[null, <ore:materialStoneTool>, null],[null, <ore:materialStoneTool>, null], [null, <ore:rodStone>, null]]);
//recipes.addShaped(<cyberware:surgery>, [[<spacex:compressed_carbonfiber>, <matteroverdrive:tritanium_ingot>, <spacex:compressed_carbonfiber>],[<matteroverdrive:tritanium_ingot>, <ore:waferBasic>, <matteroverdrive:tritanium_ingot>], [<spacex:compressed_carbonfiber>, <matteroverdrive:tritanium_ingot>, <spacex:compressed_carbonfiber>]]);
recipes.addShapeless(<minecraft:skull:1>, [<minecraft:skull>,<deepmoblearning:living_matter_hellish>]);
recipes.addShapeless(<minecraft:nether_brick> * 4, [<minecraft:stonebrick>,<deepmoblearning:living_matter_hellish>]);
recipes.addShapeless(<minecraft:netherrack> * 4, [<minecraft:cobblestone>,<deepmoblearning:living_matter_hellish>]);
recipes.addShaped(<minecraft:stone_hoe>, [[<ore:materialStoneTool>, <ore:materialStoneTool>, null],[null, <ore:rodStone>, null], [null, <ore:rodStone>, null]]);
recipes.addShaped(<minecraft:stone_axe>, [[<ore:materialStoneTool>, <ore:materialStoneTool>, null],[<ore:materialStoneTool>, <ore:rodStone>, null], [null, <ore:rodStone>, null]]);
recipes.addShaped(<minecraft:stone_shovel>, [[null, <ore:materialStoneTool>, null],[null, <ore:rodStone>, null], [null, <ore:rodStone>, null]]);
//recipes.addShapeless(<sct:stone_crafting_table>, [<sct:stone_crafting_plate>,<sct:stone_crafting_plate>,<sct:stone_crafting_plate>,<sct:stone_crafting_plate>]);
recipes.addShapeless(<minecraft:cobblestone> *2, [<galacticraftplanets:asteroids_block>,<galacticraftplanets:asteroids_block>]);
recipes.addShapeless(<minecraft:dirt> * 8, [<deepmoblearning:living_matter_overworldian>,<ezwastelands:ezwastelandblock>]);
recipes.addShapeless(<sct:stone_crafting_plate>, [<minecraft:cobblestone>,<minecraft:cobblestone>,<minecraft:cobblestone>,<minecraft:cobblestone>]);
//recipes.addShapeless(<morecharcoal:charcoal_chunk> * 8, [<pickletweaks:coal_piece:1>,<pickletweaks:coal_piece:1>,<pickletweaks:coal_piece:1>,<pickletweaks:coal_piece:1>]);
//recipes.addShapeless(<morecharcoal:charcoal_chunk> * 8, [<galacticraftplanets:carbon_fragments>,<galacticraftplanets:carbon_fragments>,<galacticraftplanets:carbon_fragments>,<galacticraftplanets:carbon_fragments>]);
recipes.addShaped(<pickletweaks:coal_piece:1> * 4, [[<galacticraftplanets:carbon_fragments>, <galacticraftplanets:carbon_fragments>, null],[<galacticraftplanets:carbon_fragments>, <galacticraftplanets:carbon_fragments>, null], [null, null, null]]);
recipes.addShaped(<pickletweaks:coal_piece> * 8, [[<galacticraftplanets:carbon_fragments>, <galacticraftplanets:carbon_fragments>, <galacticraftplanets:carbon_fragments>],[<galacticraftplanets:carbon_fragments>, <galacticraftplanets:carbon_fragments>, <galacticraftplanets:carbon_fragments>], [<galacticraftplanets:carbon_fragments>, <galacticraftplanets:carbon_fragments>, null]]);
recipes.addShapeless(<minecraft:sapling>, [<deepmoblearning:living_matter_overworldian>,<minecraft:red_mushroom>]);
recipes.addShapeless(<minecraft:sapling>, [<deepmoblearning:living_matter_overworldian>,<minecraft:brown_mushroom>]);
recipes.addShapeless(<minecraft:sapling>, [<deepmoblearning:living_matter_overworldian>,<minecraft:red_flower:8>]);
recipes.addShapeless(<minecraft:sapling>, [<deepmoblearning:living_matter_overworldian>,<minecraft:red_flower:7>]);
recipes.addShapeless(<minecraft:sapling>, [<deepmoblearning:living_matter_overworldian>,<minecraft:red_flower:6>]);
recipes.addShapeless(<minecraft:sapling>, [<deepmoblearning:living_matter_overworldian>,<minecraft:red_flower:5>]);
recipes.addShapeless(<minecraft:sapling>, [<deepmoblearning:living_matter_overworldian>,<minecraft:red_flower:4>]);
recipes.addShapeless(<minecraft:sapling>, [<deepmoblearning:living_matter_overworldian>,<minecraft:red_flower:3>]);
recipes.addShapeless(<minecraft:sapling>, [<deepmoblearning:living_matter_overworldian>,<minecraft:red_flower:2>]);
recipes.addShapeless(<minecraft:sapling>, [<deepmoblearning:living_matter_overworldian>,<minecraft:red_flower:1>]);
recipes.addShapeless(<minecraft:sapling>, [<deepmoblearning:living_matter_overworldian>,<minecraft:red_flower>]);
recipes.addShapeless(<minecraft:sapling>, [<deepmoblearning:living_matter_overworldian>,<minecraft:yellow_flower>]);
recipes.addShaped(<minecraft:stone_pickaxe>, [[<ore:cobblestone>, <ore:cobblestone>, <ore:cobblestone>],[null, <ore:rodStone>, null], [null, <ore:rodStone>, null]]);
recipes.addShapeless(<minecraft:cobblestone> * 2, [<ezwastelands:ezwastelandblock>,<ezwastelands:ezwastelandblock>]);
//File End
